name: Process Email Notifications

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  process-emails:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Email Queue
        run: |
          curl -X POST ${{ secrets.VERCEL_APP_URL }}/api/cron/process-notifications \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --max-time 30 \
            --retry 2 \
            --fail-with-body || echo "Email processing failed, will retry next minute"

      - name: Log Result
        if: always()
        run: |
          echo "Email processing job completed at $(date)" 